NASDAQ_DATA_LINK_API_KEY = "xMQVLs5ussHBFoRAZzt8"
FINMIND_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoia2Fpc2xpcGtub3QzNCIsImVtYWlsIjoicGllcmNlLmxlZS4zNEBnbWFpbC5jb20iLCJ0b2tlbl92ZXJzaW9uIjowfQ.9T3Y6zCiy5OlAlTyewu-p3THfao8Haz7jz1lj0o6J7Q"
FRED_API_KEY  = "ed9448fa848bc1100b0e82f9fcd0990c"
SEC_USER_AGENT = "Pierce Lee pierce.lee.34@gmail.com"

